repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        exclude: examples
-   repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
    -   id: yapf
